name: chex_diffusion
results_path: ../predictions
batch_size: 64
num_workers: 8

datasets:
  name: chex
  csv_path_A: ../CheXpert_noise/metadata_photon_10000.csv
  csv_path_B: ../CheXpert/metadata.csv
  dataroot_A: ../CheXpert_noise
  dataroot_B: ../CheXpert
  processed_image_root: ../processed_images/eodd/chex/chex_SDE
  split: test

models:
  network: Diffusion

task_models: 
  name: chexpert-classifier
  path: ../models/class_norm01/chex-densenet-class.pt