name: chex_unet_10000_reweighted_e10
results_path: /lotterlab/users/matteo/predictions_reweighted
batch_size: 8
num_workers: 2

datasets:
  name: chex
  csv_path_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise/metadata_photon_10000.csv
  csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise
  dataroot_B: /lotterlab/datasets/
  seed: 31415
  split: test

models:
  network: UNet
  model_path: /lotterlab/users/matteo/models/Reweighted/Chex/unet-fairness-chex-10000-reweight_20250220_114754/checkpoints/unet-fairness-chex-10000-reweight_20250220_114754_epoch_10.pth
task_models: 
  name: chexpert-classifier
  path: /lotterlab/users/matteo/code/torchxrayvision/output/class_norm01/chex-densenet-class_norm01-best.pt