name: gan_fairness-chex
results_path: ../predictions
batch_size: 16
num_workers: 4

datasets:
  name: chex
  csv_path_A: ../CheXpert_noise/metadata_photon_10000.csv
  csv_path_B: ../CheXpert/metadata.csv
  dataroot_A: ../CheXpert_noise
  dataroot_B: ../CheXpert
  seed: 31415
  split: test

models:
  network: GAN
  model_path: ../models/Pix2Pix.pth

task_models: 
  name: chexpert-classifier
  path: ../models/class_norm01/chex-densenet-class.pt