name: chex_unet_10000
results_path: ../predictions
batch_size: 8
num_workers: 2

datasets:
  name: chex
  csv_path_A: ../CheXpert_noise/metadata_photon_10000.csv
  csv_path_B: ../CheXpert/metadata.csv
  dataroot_A: ../CheXpert_noise
  dataroot_B: ../CheXpert
  seed: 31415
  split: test

models:
  network: UNet
  model_path: ../models/U-Net.pth
task_models: 
  name: chexpert-classifier
  path: ../models/class_norm01/chex-densenet-class.pt