name: chex_unet_100000
results_path: /lotterlab/users/matteo/predictions
batch_size: 8
num_workers: 2

datasets:
  name: chex
  csv_path_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise/metadata_photon_100000.csv
  csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise
  dataroot_B: /lotterlab/datasets/
  seed: 31415
  split: test

models:
  network: UNet
  model_path: /lotterlab/users/matteo/models/Noise/Chex/unet-chex-07_20250109_151718/checkpoints/unet-chex-07_20250109_151718_epoch_19_best.pth

task_models: 
  name: chexpert-classifier
  path: /lotterlab/users/matteo/code/torchxrayvision/output/class_norm01/chex-densenet-class_norm01-best.pt