name: chex_diffusion_3000
results_path: /lotterlab/users/matteo/predictions
batch_size: 8
num_workers: 1

datasets:
  name: chex
  csv_path_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise/metadata_photon_3000.csv
  csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise
  dataroot_B: /lotterlab/datasets/
  processed_image_root: /lotterlab/project_data/reconstruction_bias/processed_images/chex/chex_SDE-3000-65
  split: test

models:
  network: Diffusion

task_models: 
  name: chexpert-classifier
  path: /lotterlab/users/matteo/code/torchxrayvision/output/class_norm01/chex-densenet-class_norm01-best.pt