name: gan_fairness-chex-10000-adv-opt
results_path: /lotterlab/users/matteo/predictions_adv
batch_size: 16
num_workers: 4

datasets:
  name: chex
  csv_path_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise/metadata_photon_10000.csv
  csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise
  dataroot_B: /lotterlab/datasets/
  seed: 31415
  split: test

models:
  network: GAN
  model_path: /lotterlab/users/matteo/code/pix2pix/checkpoints/pix2pix-chex10000-128-l1000-adv-opt/200_net_G.pth

task_models: 
  name: chexpert-classifier
  path: /lotterlab/users/matteo/code/torchxrayvision/output/class_norm01/chex-densenet-class_norm01-best.pt