name: chex_diffusion_10000_adv_normalized_opt_e40
results_path: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/prediction
batch_size: 16
num_workers: 4

datasets:
  name: chex
  csv_path_A: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/data/CheXpert_noisy/chex-metadata_photon_10000.csv
  csv_path_B: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/data/CheXpert/chexpert-metadata-processed.csv
  dataroot_A: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/data/CheXpert_noisy
  dataroot_B: /vol/miltank/datasets/CheXpert 
  processed_image_root: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/data/processed/chex/chex_SDE-10000-adv-normalized-opt-e40
  split: test

models:
  network: Diffusion

task_models: 
  name: chexpert-classifier
  path: /vol/miltank/projects/practical_SoSe24/mri_inr/matteo/code/torchxrayvision/chex-densenet-class_norm01-best.pt