name: gan_fairness-ucsf-08-l0005-t03-ce05
results_path: /lotterlab/users/matteo/predictions-EODD-fairness
batch_size: 16
num_workers: 4

datasets:
  name: ucsf
  dataroot: /lotterlab/users/matteo/data/UCSF-PDGM
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: GAN
  model_path: /lotterlab/users/matteo/models/EODD-Fairness/pix2pix-ucsf8-128-l1000-fairness-t03-ce05/200_net_G.pth
  
task_models: 
  name: ucsf
  models: 
    - type: classifier
      name: TGradeBCEClassifier
      path: /lotterlab/users/matteo/models/tgrade/checkpoints/tgrade_test_20240925_113550_epoch_1_best.pth
    - type: classifier
      name: TTypeBCEClassifier
      path: /lotterlab/users/matteo/models/ttype/checkpoints/ttype_test_20240925_113544_epoch_1_best.pth
    - type: segmentation
      name: UNet
      path: /lotterlab/users/matteo/models/segmentation_skews/segmentation_20241126_225621/checkpoints/segmentation_20241126_225621_epoch_11.pth