name: ucsf_unet_8_fairness
results_path: /lotterlab/users/matteo/predictions
batch_size: 8
num_workers: 2

datasets:
  name: ucsf
  dataroot: /lotterlab/users/matteo/data/UCSF-PDGM
  sampling_mask: radial
  seed: 31415
  type: FLAIR
  pathology: []
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: UNet
  model_path: /lotterlab/users/matteo/code/recon_bias/output/unet-fairness-ucsf-08-001_20250213_135512/checkpoints/unet-fairness-ucsf-08-001_20250213_135512_epoch_19_best.pth

task_models: 
  name: ucsf
  models: 
    - type: classifier
      name: TGradeBCEClassifier
      path: /lotterlab/users/matteo/models/tgrade/checkpoints/tgrade_test_20240925_113550_epoch_1_best.pth
    - type: classifier
      name: TTypeBCEClassifier
      path: /lotterlab/users/matteo/models/ttype/checkpoints/ttype_test_20240925_113544_epoch_1_best.pth
    - type: segmentation
      name: UNet
      path: /lotterlab/users/matteo/models/segmentation_skews/segmentation_20241126_225621/checkpoints/segmentation_20241126_225621_epoch_11.pth
    