name: gan_ucsf
results_path: ../predictions
batch_size: 16
num_workers: 4

datasets:
  name: ucsf
  dataroot: ../UCSF-PDGM
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: GAN
  model_path: ../models/Pix2Pix.pth
  
task_models: 
  name: ucsf
  models: 
    - type: classifier
      name: TGradeBCEClassifier
      path: ../models/tgrade/checkpoints/tgrade.pth
    - type: classifier
      name: TTypeBCEClassifier
      path: ../models/ttype/checkpoints/ttype.pth
    - type: segmentation
      name: UNet
      path: ../models/segmentation/segmentation.pth