name: ucsf_diffusion_8_adv_e316
results_path: /lotterlab/users/matteo/predictions_adv
batch_size: 16
num_workers: 4

datasets:
  name: ucsf
  dataroot: /lotterlab/users/matteo/data/UCSF-PDGM
  processed_image_root: /lotterlab/project_data/reconstruction_bias/processed_images/adv/ucsf/ucsf_SDE-8-adv-e316
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: Diffusion

task_models: 
  name: ucsf
  models: 
    - type: classifier
      name: TGradeBCEClassifier
      path: /lotterlab/users/matteo/models/tgrade/checkpoints/tgrade_test_20240925_113550_epoch_1_best.pth
    - type: classifier
      name: TTypeBCEClassifier
      path: /lotterlab/users/matteo/models/ttype/checkpoints/ttype_test_20240925_113544_epoch_1_best.pth
    - type: segmentation
      name: UNet
      path: /lotterlab/users/matteo/models/segmentation_skews/segmentation_20241126_225621/checkpoints/segmentation_20241126_225621_epoch_11.pth