name: ucsf_unet
results_path: ../predictions
batch_size: 64
num_workers: 8

datasets:
  name: ucsf
  dataroot: ../UCSF-PDGM
  sampling_mask: radial
  seed: 31415
  type: FLAIR
  pathology: []
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: UNet
  model_path: ../models/U-Net.pth
task_models: 
  name: ucsf
  models: 
    - type: classifier
      name: TGradeBCEClassifier
      path: ../models/tgrade/checkpoints/tgrade.pth
    - type: classifier
      name: TTypeBCEClassifier
      path: ../models/ttype/checkpoints/ttype.pth
    - type: segmentation
      name: UNet
      path: ../models/segmentation/segmentation.pth
    