name: ucsf_unet_reconstruction_test
results_path: /lotterlab/project_data/reconstruction_bias/processed_images/ucsf
batch_size: 8
num_workers: 2

datasets:
  name: ucsf
  number_of_samples: 10
  dataroot: /lotterlab/users/matteo/data/UCSF-PDGM
  sampling_mask: radial
  seed: 31415
  type: FLAIR
  pathology: []
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 140

models:
  network: UNet
  model_path: /lotterlab/users/matteo/models/Noise/UCSF/Unet/unet-4_20250129_184319/checkpoints/unet-4_20250129_184319_epoch_19_best.pth

task_models: 
  name: ucsf
  models: 
    - type: classifier
      name: TGradeBCEClassifier
      path: /lotterlab/users/matteo/models/tgrade/checkpoints/tgrade_test_20240925_113550_epoch_1_best.pth
    - type: classifier
      name: TTypeBCEClassifier
      path: /lotterlab/users/matteo/models/ttype/checkpoints/ttype_test_20240925_113544_epoch_1_best.pth
    - type: segmentation
      name: UNet
      path: /lotterlab/users/matteo/models/segmentation_skews/segmentation_20241126_225621/checkpoints/segmentation_20241126_225621_epoch_11.pth
    