name: ucsf_gan_reconstruction
results_path: /lotterlab/project_data/reconstruction_bias/processed_images/ucsf
batch_size: 32
num_workers: 8

paths:
  recon_bias: /lotterlab/users/matteo/code/recon_bias
  pix2pix: /lotterlab/users/matteo/code/pix2pix
  sde: /lotterlab/users/matteo/code/image-restoration-sde

datasets:
  name: ucsf
  dataroot: /lotterlab/users/matteo/data/UCSF-PDGM
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 140

models:
  network: GAN
  model_path: /lotterlab/users/matteo/models/Noise/UCSF/UCSF-4/pix2pix-ucsf-128-4-e200.pth