name: chex_unet_reconstruction
results_path: ./results
batch_size: 32
num_workers: 8

paths:
  recon_bias: /lotterlab/users/matteo/code/recon_bias
  pix2pix: /lotterlab/users/matteo/code/pix2pix
  sde: /lotterlab/users/matteo/code/image-restoration-sde


datasets:
  name: chex
  csv_path_A: /lotterlab/project_data/CheXpert_noise/metadata_photon_100000.csv
  csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_A: /lotterlab/project_data/CheXpert_noise
  dataroot_B: /lotterlab/datasets/
  seed: 31415
  split: test

models:
  network: UNet
  model_path: /lotterlab/users/matteo/models/Noise/Chex/unet-chex-05_20250107_144825/checkpoints/unet-chex-05_20250107_144825_epoch_20_final.pth