name: chex_diffusion_reconstruction
results_path: ./results
batch_size: 8
num_workers: 2

paths:
  recon_bias: /lotterlab/users/matteo/code/recon_bias
  pix2pix: /lotterlab/users/matteo/code/pix2pix
  sde: /lotterlab/users/matteo/code/image-restoration-sde

datasets:
  name: chex
  csv_path_A: /lotterlab/project_data/CheXpert_noise/metadata_photon_100000.csv
  csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_A: /lotterlab/project_data/CheXpert_noise
  dataroot_B: /lotterlab/datasets/
  seed: 31415
  split: test

models:
  network: Diffusion

model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  
degradation:
  # for denoising
  sigma: 25
  noise_type: G


network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

path:
  pretrain_model_G: /lotterlab/users/matteo/models/Noise/Chex/Diffusion/SDE-10000-40_G.pth
  strict_load: True
