name: chex_SDE-10000-reweighted-20
results_path: /lotterlab/project_data/reconstruction_bias/processed_images/reweight/chex
batch_size: 16
num_workers: 4

paths:
  recon_bias: /lotterlab/users/matteo/code/recon_bias
  pix2pix: /lotterlab/users/matteo/code/pix2pix
  sde: /lotterlab/users/matteo/code/image-restoration-sde

datasets:
  name: chex
  csv_path_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise/metadata_photon_10000.csv
  csv_path_B: /lotterlab/users/matteo/data/CheXpert/metadata.csv
  dataroot_A: /lotterlab/project_data/reconstruction_bias/CheXpert_noise
  dataroot_B: /lotterlab/datasets/
  seed: 31415
  split: test

models:
  network: Diffusion

model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  
degradation:
  # for denoising
  sigma: 25
  noise_type: G


network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

path:
  pretrain_model_G: /lotterlab/users/matteo/models/Reweighted/Chex/chex10000-sde-reweight/models/20_G.pth
  strict_load: True
