name: ucsf_SDE-8-reweight-50
results_path: /lotterlab/project_data/reconstruction_bias/processed_images/reweight/ucsf
batch_size: 4
num_workers: 2

paths:
  recon_bias: /lotterlab/users/matteo/code/recon_bias
  pix2pix: /lotterlab/users/matteo/code/pix2pix
  sde: /lotterlab/users/matteo/code/image-restoration-sde

datasets:
  name: ucsf
  dataroot: /lotterlab/users/matteo/data/UCSF-PDGM
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: Diffusion

model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  
degradation:
  # for denoising
  sigma: 25
  noise_type: G


network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

path:
  pretrain_model_G: /lotterlab/users/matteo/models/Reweighted/UCSF/ucsf-sde-8-reweight/models/50_G.pth
  strict_load: True
