name: ucsf_unet_reconstruction
results_path: ./results
batch_size: 32
num_workers: 8

paths:
  recon_bias: /lotterlab/users/matteo/code/recon_bias
  pix2pix: /lotterlab/users/matteo/code/pix2pix
  sde: /lotterlab/users/matteo/code/image-restoration-sde

datasets:
  name: ucsf
  dataroot: /lotterlab/users/matteo/data/UCSF-PDGM
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 140

models:
  network: UNet
  model_path: /lotterlab/users/matteo/models/Noise/UCSF/unet-4_20250129_184319/checkpoints/unet-4_20250129_184319_epoch_19_best.pth