name: ucsf_SDE  
results_path: ../processed_images/eodd/ucsf
batch_size: 16
num_workers: 4

paths:  
  recon_bias: ../recon_bias
  pix2pix: ../pix2pix
  sde: ../image-restoration-sde

datasets:
  name: ucsf
  dataroot: ../UCSF-PDGM
  sampling_mask: radial  # or linear
  seed: 31415
  type: FLAIR  # or other MRI type
  pathology: []  # list of pathologies to include
  lower_slice: 60
  upper_slice: 130
  split: test
  num_rays: 60

models:
  network: Diffusion

model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  
degradation:
  # for denoising
  sigma: 25
  noise_type: G


network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 64
    depth: 4

path:
  pretrain_model_G: ../image-restoration-sde.pth
  strict_load: True
